version: '3.8'

services:
  app:
    image: kumarthe799/dockerdemofeb:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bike?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: omsairam
      MYSQL_DATABASE: bike
      MYSQL_USER: root
      MYSQL_PASSWORD: omsairam
